<a href="https://colab.research.google.com/github/raviiraj13/100_days_of_Data_Science/blob/main/Numpy_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#creating array from list

In [5]:
arr_1d=np.array([1,2,3,4,5])
arr_1d


array([1, 2, 3, 4, 5])

In [6]:
print(arr_1d)

[1 2 3 4 5]


In [7]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Attributes

for 1d array

In [9]:
arr_1d.dtype

dtype('int64')

In [10]:
arr_1d.shape

(5,)

In [11]:
arr_1d.size

5

In [12]:
arr_1d.ndim

1

for 2d array

In [13]:
arr_2d.shape

(3, 3)

In [14]:
arr_2d.size

9

In [15]:
arr_2d.ndim

2

In [16]:
arr_2d.dtype

dtype('int64')

#Creating new array of Selective type

In [18]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
ones_1d=np.ones(5)
ones_1d

array([1., 1., 1., 1., 1.])

In [24]:
full = np.full((3,4),7)
full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [25]:
nums = np.arange(1,11)
print(nums)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
nums=np.arange(1,11,2)
print(nums)

[1 3 5 7 9]


In [27]:
nums = np.linspace(0,1,5)
nums

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
empty = np.empty((2,2))
empty

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

#Creating a new array based on an existing one

In [33]:
old_arr = np.array([4,3,5,6,2,4,1])
print(old_arr)

[4 3 5 6 2 4 1]


In [34]:
new_arr = old_arr.copy()
print(new_arr)

[4 3 5 6 2 4 1]


#Random array generation

In [39]:
arr1 = np.random.random((3,4))
print(arr1)

[[0.21685437 0.34601125 0.55504076 0.70513409]
 [0.15277197 0.93905933 0.98280101 0.55760073]
 [0.05603502 0.1253561  0.9525081  0.70622115]]


In [40]:
arr2 = np.random.rand(3,3)
arr2

array([[0.8906976 , 0.20059676, 0.40456344],
       [0.38644965, 0.55688987, 0.62434644],
       [0.88473652, 0.16366015, 0.73552952]])

In [41]:
arr3 = np.random.randn(2,4)
arr3

array([[-1.09498518, -0.76552793,  0.14487205, -1.44419168],
       [-1.32103215,  1.47073323,  0.88521375, -2.13729688]])

#Reshaping

In [43]:
demo = np.arange(1,11)
print(demo)

[ 1  2  3  4  5  6  7  8  9 10]


In [45]:
demo_reshaped = demo.reshape(2,5)
print(demo_reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [46]:
demo2 = np.arange(1,16).reshape(5,3)
print(demo2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [48]:
unflat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(unflat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
flat = unflat.flatten()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [50]:
flat  = unflat.ravel()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [58]:
arr=np.array([[1,8,7],[2,3,6],[3,2,3]])
print(arr,"\n")
print(arr.T)

[[1 8 7]
 [2 3 6]
 [3 2 3]] 

[[1 2 3]
 [8 3 2]
 [7 6 3]]


In [59]:
arr[1] #give 2 row with index 1

array([2, 3, 6])

In [60]:
arr[:,1] #give 2 column with index 1

array([8, 3, 2])

In [62]:
arr[2,1] #give  element at index 2,3 means 3 row(index=2) and 2 column(index=1)

np.int64(2)

#Slicing

In [71]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
print(arr[2:8])

[2 3 4 5 6 7]


In [66]:
print(arr[:7])

[0 1 2 3 4 5 6]


In [67]:
print(arr[5:])

[5 6 7 8 9]


In [ ]:
print(arr[::2]) #[0 2 4 6 8] (every 2nd element)

In [ ]:
print(arr([::-1]))  # [9 8 7 6 5 4 3 2 1 0] (reverse array)

In [68]:
print(arr[-7:-1])

[3 4 5 6 7 8]


slicing whole row

In [73]:
demo = np.arange(1,31).reshape(6,5)
print(demo)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [77]:
print(demo[1]) #slicing 2nd row index = 1 also write demo[1,:]

[ 6  7  8  9 10]


In [76]:
print(demo[:,1]) #slicing 2 column index=1

[ 2  7 12 17 22 27]


2d array slicing

In [78]:
demo

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [80]:
print(demo[1:3,1:4])

[[ 7  8  9]
 [12 13 14]]


#Sorting

In [72]:
unsorted = np.array([5,4,26,4,56,7,5,3,5])
sorted = np.sort(unsorted)
print(sorted)

[ 3  4  4  5  5  5  7 26 56]


#Filter

In [81]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [83]:
#for printing even number from arr
mask = arr % 2 == 0
print(arr[mask])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [84]:
#number greater than 50
print(arr>50)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


In [85]:
print(arr[arr>50])

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


indexing & Fancy Indexing

In [87]:
print(arr[0])

1


In [90]:
index = [0,5,6]
print(arr[[0,5,7]])

[1 6 8]


#Adding & Removing Data

In [91]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


In [92]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
combined = np.concatenate((arr1,arr2),axis=0)
print(combined)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [94]:
combined = np.concatenate((arr1,arr2),axis=1)
print(combined)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [96]:
demo = np.array([1,2,3,4,5])
demo_a=np.delete(demo,2)
print(demo_a)

[1 2 4 5]


#Mathematical Operations

1. Basic Arithmetic Operations

In [99]:
#All Operations are perfomed element wise
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b,"\n")
print(a-b,"\n")
print(a*b,"\n")
print(a/b,"\n")
print(a**b,"\n")
print(a%b)

[5 7 9] 

[-3 -3 -3] 

[ 4 10 18] 

[0.25 0.4  0.5 ] 

[  1  32 729] 

[1 2 3]


2.Universal Mathematical Functions

In [ ]:

print(np.sqrt(a))


print(np.exp(a))


print(np.log(a))


print(np.sin(a))   # [0.84147098 0.90929743 0.14112001]
print(np.cos(a))   # [0.54030231 -0.41614684 -0.9899925]


3. Aggregation Functions

In [100]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))       # 15
print(np.mean(arr))      # 3.0
print(np.std(arr))       # 1.414213562
print(np.min(arr))       # 1
print(np.max(arr))       # 5


15
3.0
1.4142135623730951
1
5


In [101]:
matrix = np.array([[1,2,3],[4,5,6]])
print(np.sum(matrix, axis=0))  # sum along columns: [5 7 9]
print(np.sum(matrix, axis=1))  # sum along rows: [6 15]


[5 7 9]
[ 6 15]


In [102]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Matrix multiplication
print(np.dot(A, B))
# [[19 22]
#  [43 50]]

# Transpose
print(A.T)
# [[1 3]
#  [2 4]]

# Determinant
print(np.linalg.det(A))  # -2.0


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
-2.0000000000000004


In [103]:
A@B #for matrix multiplication

array([[19, 22],
       [43, 50]])